---
site_name: Groupstage
copyright: Football bloody hell

theme:
  name: material
  language: da
  favicon: favicon.ico

extra_css:
  - 'css/groupstage.css'

markdown_extensions:
  - toc:
      permalink: "#"

plugins:
  - search:
      lang: da
  - table-reader:
      data_path: 'docs'
  - macros:

nav:
  - 'Hvad er det her?': index.md
  - 'Slutrunder':
      - 'VM 2022':
          - 'Deltag': slutrunder/vm2022/deltag.md
          - 'Stillingen': slutrunder/vm2022/stillingen.md
          - 'Alle tips': resources/vm2022/vm2022-stillingen.html      
      - 'CL 2021/2021':
          - 'Deltag': slutrunder/cl2122/deltag.md
          - 'Stillingen': slutrunder/cl2122/stillingen.md
          - 'Alle tips': resources/cl2122/cl2122-stillingen.html
      - 'EM 2020':
          - 'Deltag': slutrunder/em2020/deltag.md
          - 'Stillingen': slutrunder/em2020/stillingen.md
          - 'Alle tips': resources/em2020/em2020-stillingen.html
  - 'Reglerne': reglerne.md
  - 'Præmier': praemier.md
  - 'Hall of fame': halloffame.md
...