---
site_name: Groupstage
copyright: Football bloody hell

theme:
  name: material
  language: da

extra_css:
  - 'css/groupstage.css'

plugins:
  - search:
      lang: da
  - table-reader:
      data_path: "docs"
  - macros:

nav:
  - 'Hvad er det her?': index.md
  - 'Slutrunder':
      - 'EM 2020':
          - 'Deltag': slutrunder/em2020/deltag.md
          - 'Stillingen': slutrunder/em2020/stillingen.md
          - 'Alle tips': resources/em2020/em2020-stillingen.html
  - 'Reglerne': reglerne.md
  - 'Præmier': praemier.md
...